### ISSUE TITLE
Split ADC logic as a device

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/intel-aero-fpga#6]
@zehortigoza like you did with the other parts, can we split the ADC logic from top.v to be a I2C slave?  Ideally we would use the same I2C bridge implementation to bridge I2C to the external pins, and just have the ADC logic be an "internal I2C device", separate from top.v.

**Comment by zehortigoza** [comment]
https://github.com/intel-aero/intel-aero-fpga/pull/7
